#!/bin/bash

# Install LaTeX
apt-get update
apt-get install -y texlive texlive-latex-extra

# Install any additional LaTeX packages you may need
# For example, to install 'latexmk':
# apt-get install -y latexmk

# Install Node.js dependencies (if applicable)
npm install

# Compile LaTeX files
pdflatex -output-directory=/tmp -interaction=nonstopmode /tmp/resume.tex

# Move generated PDF to public folder (adjust paths as needed)
mkdir -p public
mv /tmp/resume.pdf public/resume.pdf

# Clean up auxiliary files generated by LaTeX
rm /tmp/resume.*

# Run Vercel deployment command
# This command deploys your project to Vercel
vercel --token=$VERCEL_TOKEN --prod
